# gruvbox_dark
[colors.bright]
black = "0x928374"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfabd2f"

[colors.normal]
black = "0x282828"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0xa89984"
yellow = "0xd79921"

[colors.primary]
background = "0x282828"
foreground = "0xebdbb2"

# gruvbox_light
# [colors.bright]
# black = "0x928374"
# blue = "0x076678"
# cyan = "0x427b58"
# green = "0x79740e"
# magenta = "0x8f3f71"
# red = "0x9d0006"
# white = "0x3c3836"
# yellow = "0xb57614"

# [colors.normal]
# black = "0xfbf1c7"
# blue = "0x458588"
# cyan = "0x689d6a"
# green = "0x98971a"
# magenta = "0xb16286"
# red = "0xcc241d"
# white = "0x7c6f64"
# yellow = "0xd79921"

# [colors.primary]
# background = "0xfbf1c7"
# foreground = "0x3c3836"

# papercolor_dark
# [colors.bright]
# black = "0xd7af5f"
# blue = "0x5fafd7"
# cyan = "0x5f8787"
# green = "0x5faf5f"
# magenta = "0xd7875f"
# red = "0xaf005f"
# white = "0xd0d0d0"
# yellow = "0x5faf00"

# [colors.normal]
# black = "0x1c1c1c"
# blue = "0xff5faf"
# cyan = "0xffaf00"
# green = "0xaf87d7"
# magenta = "0x00afaf"
# red = "0x585858"
# white = "0x808080"
# yellow = "0xafd700"

# [colors.primary]
# background = "0x1c1c1c"
# foreground = "0x808080"

# papercolor_light
# [colors.bright]
# black = "0x969694"
# blue = "0x4271ae"
# cyan = "0x3e999f"
# green = "0x718c00"
# magenta = "0x8959a8"
# red = "0xd7005f"
# white = "0xf5f5f5"
# yellow = "0xd75f00"

# [colors.normal]
# black = "0xededed"
# blue = "0x4271ae"
# cyan = "0x3e999f"
# green = "0x718c00"
# magenta = "0x8959a8"
# red = "0xd7005f"
# white = "0x4d4d4c"
# yellow = "0xd75f00"

# [colors.primary]
# background = "0xeeeeee"
# foreground = "0x4d4d4c"

# solarized_dark
# [colors.bright]
# black = "0x002b36"
# blue = "0x839496"
# cyan = "0x93a1a1"
# green = "0x586e75"
# magenta = "0x6c71c4"
# red = "0xcb4b16"
# white = "0xfdf6e3"
# yellow = "0x657b83"

# [colors.cursor]
# cursor = "0x839495"
# text = "0x002b36"

# [colors.normal]
# black = "0x073642"
# blue = "0x268bd2"
# cyan = "0x2aa198"
# green = "0x859900"
# magenta = "0xd33682"
# red = "0xdc322f"
# white = "0xeee8d5"
# yellow = "0xb58900"

# [colors.primary]
# background = "0x002b36"
# foreground = "0x839496"

# solarized_light
# [colors.bright]
# black = "0x002b36"
# blue = "0x839496"
# cyan = "0x93a1a1"
# green = "0x586e75"
# magenta = "0x6c71c4"
# red = "0xcb4b16"
# white = "0xfdf6e3"
# yellow = "0x657b83"

# [colors.cursor]
# cursor = "0x657b83"
# text = "0xfdf6e3"

# [colors.normal]
# black = "0x073642"
# blue = "0x268bd2"
# cyan = "0x2aa198"
# green = "0x859900"
# magenta = "0xd33682"
# red = "0xdc322f"
# white = "0xeee8d5"
# yellow = "0xb58900"

# [colors.primary]
# background = "0xfdf6e3"
# foreground = "0x657b83"

[font]
size = 12.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.glyph_offset]
y = 5

[font.normal]
family = "FiraCode Nerd Font"
style = "Light"

[font.offset]
y = 9

[mouse]
hide_when_typing = false

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = false
startup_mode = "Maximized"
opacity = 0.999999  # Workaround to fix stuttering window animation issue
